name: CI

on:
  push:
    branches: [ main, dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1

      - uses: actions/checkout@v4

      - name: Linting
        run: deno lint
        
      - name: Formatting
        run: deno fmt --check

      - name: Testing
        run: deno test -A

      - name: Build
        run: deno task build

      - name: Pre-publish checks
        run: deno publish --dry-run

