name: CI

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: denoland/setup-deno@v1

      - uses: actions/checkout@v4

      - name: Linting
        run: deno lint
        
      - name: Formatting
        run: deno fmt --check

      - name: Testing
        run: deno test -A

      - name: Build
        run: deno task build

      - name: Pre-publish checks
        run: deno publish --dry-run

      - name: Build
        run: deno task build

      - name: Publish to JSR 
        if: "contains(github.event.head_commit.message, '@publish')"
        run: deno publish

