name: CI

on:
  push:
    branches: [ main, dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - uses: actions/checkout@v4

      - name: Linting
        run: deno lint

      - name: Testing
        run: deno test -A

      - name: Pre-publish checks
        run: deno publish --dry-run

