name: JSR

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/checkout@v4
      - name: Build
        run: deno task build
      - name: Publish to JSR 
        run: deno publish
