name: CI/CD

on:
  push:
    branches: [ main, dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{steps.release.outputs.release_created}}
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - uses: actions/checkout@v4

      - name: Linting
        run: deno lint

      - name: Run tests
        run: deno test -A

